/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SaasAdminRouteImport } from './routes/saas-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as InscripcionRouteImport } from './routes/inscripcion'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerCardTokenRouteImport } from './routes/player-card.$token'
import { Route as AppWorkflowsRouteImport } from './routes/_app/workflows'
import { Route as AppTiendaRouteImport } from './routes/_app/tienda'
import { Route as AppTemporadasRouteImport } from './routes/_app/temporadas'
import { Route as AppTacticaRouteImport } from './routes/_app/tactica'
import { Route as AppSoporteRouteImport } from './routes/_app/soporte'
import { Route as AppSedesRouteImport } from './routes/_app/sedes'
import { Route as AppRutaAprendizajeRouteImport } from './routes/_app/ruta-aprendizaje'
import { Route as AppRetencionRouteImport } from './routes/_app/retencion'
import { Route as AppReportesRouteImport } from './routes/_app/reportes'
import { Route as AppRendimientoRouteImport } from './routes/_app/rendimiento'
import { Route as AppPruebasRouteImport } from './routes/_app/pruebas'
import { Route as AppProspectosRouteImport } from './routes/_app/prospectos'
import { Route as AppPosicionesRouteImport } from './routes/_app/posiciones'
import { Route as AppPlantillasRouteImport } from './routes/_app/plantillas'
import { Route as AppPartidosRouteImport } from './routes/_app/partidos'
import { Route as AppPagosRouteImport } from './routes/_app/pagos'
import { Route as AppOperacionRouteImport } from './routes/_app/operacion'
import { Route as AppObjetivosRouteImport } from './routes/_app/objetivos'
import { Route as AppNotificacionesRouteImport } from './routes/_app/notificaciones'
import { Route as AppMuroRouteImport } from './routes/_app/muro'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppInventarioRouteImport } from './routes/_app/inventario'
import { Route as AppInstalacionesRouteImport } from './routes/_app/instalaciones'
import { Route as AppIaRouteImport } from './routes/_app/ia'
import { Route as AppHorariosRouteImport } from './routes/_app/horarios'
import { Route as AppFinanzasRouteImport } from './routes/_app/finanzas'
import { Route as AppFacturacionRouteImport } from './routes/_app/facturacion'
import { Route as AppEvaluacionesRouteImport } from './routes/_app/evaluaciones'
import { Route as AppEquiposRouteImport } from './routes/_app/equipos'
import { Route as AppEntrenamientosRouteImport } from './routes/_app/entrenamientos'
import { Route as AppEncargadosRouteImport } from './routes/_app/encargados'
import { Route as AppEgresosRouteImport } from './routes/_app/egresos'
import { Route as AppDisciplinasRouteImport } from './routes/_app/disciplinas'
import { Route as AppDiarioRouteImport } from './routes/_app/diario'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCrmRouteImport } from './routes/_app/crm'
import { Route as AppConvocatoriasRouteImport } from './routes/_app/convocatorias'
import { Route as AppConfiguracionRouteImport } from './routes/_app/configuracion'
import { Route as AppComunicacionesRouteImport } from './routes/_app/comunicaciones'
import { Route as AppCompeticionesRouteImport } from './routes/_app/competiciones'
import { Route as AppCoachRouteImport } from './routes/_app/coach'
import { Route as AppCheckinRouteImport } from './routes/_app/checkin'
import { Route as AppCategoriasRouteImport } from './routes/_app/categorias'
import { Route as AppCargaRouteImport } from './routes/_app/carga'
import { Route as AppCampanasRouteImport } from './routes/_app/campanas'
import { Route as AppCalendarioRouteImport } from './routes/_app/calendario'
import { Route as AppCajaRouteImport } from './routes/_app/caja'
import { Route as AppBibliotecaRouteImport } from './routes/_app/biblioteca'
import { Route as AppBalanceRouteImport } from './routes/_app/balance'
import { Route as AppAuditoriaRouteImport } from './routes/_app/auditoria'
import { Route as AppAsistenciaStaffRouteImport } from './routes/_app/asistencia-staff'
import { Route as AppAsistenciaRouteImport } from './routes/_app/asistencia'
import { Route as AppTacticaIndexRouteImport } from './routes/_app/tactica.index'
import { Route as AppRendimientoIndexRouteImport } from './routes/_app/rendimiento.index'
import { Route as AppMedicoIndexRouteImport } from './routes/_app/medico.index'
import { Route as AppJugadoresIndexRouteImport } from './routes/_app/jugadores.index'
import { Route as AppEntrenadoresIndexRouteImport } from './routes/_app/entrenadores.index'
import { Route as AppTacticaVideoRouteImport } from './routes/_app/tactica.video'
import { Route as AppTacticaSimulacionesRouteImport } from './routes/_app/tactica.simulaciones'
import { Route as AppTacticaRivalesRouteImport } from './routes/_app/tactica.rivales'
import { Route as AppTacticaPostpartidoRouteImport } from './routes/_app/tactica.postpartido'
import { Route as AppTacticaPlanificacionRouteImport } from './routes/_app/tactica.planificacion'
import { Route as AppTacticaPizarraRouteImport } from './routes/_app/tactica.pizarra'
import { Route as AppTacticaMatrizRouteImport } from './routes/_app/tactica.matriz'
import { Route as AppTacticaJugadasRouteImport } from './routes/_app/tactica.jugadas'
import { Route as AppTacticaFormacionesRouteImport } from './routes/_app/tactica.formaciones'
import { Route as AppTacticaEstrategiasRouteImport } from './routes/_app/tactica.estrategias'
import { Route as AppTacticaBibliotecaRouteImport } from './routes/_app/tactica.biblioteca'
import { Route as AppTacticaAnalisisIaRouteImport } from './routes/_app/tactica.analisis-ia'
import { Route as AppRendimientoWellnessRouteImport } from './routes/_app/rendimiento.wellness'
import { Route as AppRendimientoTestsRouteImport } from './routes/_app/rendimiento.tests'
import { Route as AppRendimientoSportsScienceRouteImport } from './routes/_app/rendimiento.sports-science'
import { Route as AppRendimientoPlanificacionRouteImport } from './routes/_app/rendimiento.planificacion'
import { Route as AppRendimientoLesionesRouteImport } from './routes/_app/rendimiento.lesiones'
import { Route as AppRendimientoGpsRouteImport } from './routes/_app/rendimiento.gps'
import { Route as AppRendimientoCargasRouteImport } from './routes/_app/rendimiento.cargas'
import { Route as AppMedicoCitasRouteImport } from './routes/_app/medico.citas'
import { Route as AppJugadoresIdRouteImport } from './routes/_app/jugadores.$id'
import { Route as AppIaRiesgosRouteImport } from './routes/_app/ia.riesgos'
import { Route as AppIaRecomendacionesRouteImport } from './routes/_app/ia.recomendaciones'
import { Route as AppIaPrediccionesRouteImport } from './routes/_app/ia.predicciones'
import { Route as AppIaInsightsRouteImport } from './routes/_app/ia.insights'
import { Route as AppIaAsistenteRouteImport } from './routes/_app/ia.asistente'
import { Route as AppEntrenadoresIdRouteImport } from './routes/_app/entrenadores.$id'
import { Route as AppMedicoJugadorIdRouteImport } from './routes/_app/medico.jugador.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SaasAdminRoute = SaasAdminRouteImport.update({
  id: '/saas-admin',
  path: '/saas-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const InscripcionRoute = InscripcionRouteImport.update({
  id: '/inscripcion',
  path: '/inscripcion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerCardTokenRoute = PlayerCardTokenRouteImport.update({
  id: '/player-card/$token',
  path: '/player-card/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppTiendaRoute = AppTiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => AppRoute,
} as any)
const AppTemporadasRoute = AppTemporadasRouteImport.update({
  id: '/temporadas',
  path: '/temporadas',
  getParentRoute: () => AppRoute,
} as any)
const AppTacticaRoute = AppTacticaRouteImport.update({
  id: '/tactica',
  path: '/tactica',
  getParentRoute: () => AppRoute,
} as any)
const AppSoporteRoute = AppSoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => AppRoute,
} as any)
const AppSedesRoute = AppSedesRouteImport.update({
  id: '/sedes',
  path: '/sedes',
  getParentRoute: () => AppRoute,
} as any)
const AppRutaAprendizajeRoute = AppRutaAprendizajeRouteImport.update({
  id: '/ruta-aprendizaje',
  path: '/ruta-aprendizaje',
  getParentRoute: () => AppRoute,
} as any)
const AppRetencionRoute = AppRetencionRouteImport.update({
  id: '/retencion',
  path: '/retencion',
  getParentRoute: () => AppRoute,
} as any)
const AppReportesRoute = AppReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AppRoute,
} as any)
const AppRendimientoRoute = AppRendimientoRouteImport.update({
  id: '/rendimiento',
  path: '/rendimiento',
  getParentRoute: () => AppRoute,
} as any)
const AppPruebasRoute = AppPruebasRouteImport.update({
  id: '/pruebas',
  path: '/pruebas',
  getParentRoute: () => AppRoute,
} as any)
const AppProspectosRoute = AppProspectosRouteImport.update({
  id: '/prospectos',
  path: '/prospectos',
  getParentRoute: () => AppRoute,
} as any)
const AppPosicionesRoute = AppPosicionesRouteImport.update({
  id: '/posiciones',
  path: '/posiciones',
  getParentRoute: () => AppRoute,
} as any)
const AppPlantillasRoute = AppPlantillasRouteImport.update({
  id: '/plantillas',
  path: '/plantillas',
  getParentRoute: () => AppRoute,
} as any)
const AppPartidosRoute = AppPartidosRouteImport.update({
  id: '/partidos',
  path: '/partidos',
  getParentRoute: () => AppRoute,
} as any)
const AppPagosRoute = AppPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AppRoute,
} as any)
const AppOperacionRoute = AppOperacionRouteImport.update({
  id: '/operacion',
  path: '/operacion',
  getParentRoute: () => AppRoute,
} as any)
const AppObjetivosRoute = AppObjetivosRouteImport.update({
  id: '/objetivos',
  path: '/objetivos',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacionesRoute = AppNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppMuroRoute = AppMuroRouteImport.update({
  id: '/muro',
  path: '/muro',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppInventarioRoute = AppInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AppRoute,
} as any)
const AppInstalacionesRoute = AppInstalacionesRouteImport.update({
  id: '/instalaciones',
  path: '/instalaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppHorariosRoute = AppHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanzasRoute = AppFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AppRoute,
} as any)
const AppFacturacionRoute = AppFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => AppRoute,
} as any)
const AppEvaluacionesRoute = AppEvaluacionesRouteImport.update({
  id: '/evaluaciones',
  path: '/evaluaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppEquiposRoute = AppEquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrenamientosRoute = AppEntrenamientosRouteImport.update({
  id: '/entrenamientos',
  path: '/entrenamientos',
  getParentRoute: () => AppRoute,
} as any)
const AppEncargadosRoute = AppEncargadosRouteImport.update({
  id: '/encargados',
  path: '/encargados',
  getParentRoute: () => AppRoute,
} as any)
const AppEgresosRoute = AppEgresosRouteImport.update({
  id: '/egresos',
  path: '/egresos',
  getParentRoute: () => AppRoute,
} as any)
const AppDisciplinasRoute = AppDisciplinasRouteImport.update({
  id: '/disciplinas',
  path: '/disciplinas',
  getParentRoute: () => AppRoute,
} as any)
const AppDiarioRoute = AppDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppConvocatoriasRoute = AppConvocatoriasRouteImport.update({
  id: '/convocatorias',
  path: '/convocatorias',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppComunicacionesRoute = AppComunicacionesRouteImport.update({
  id: '/comunicaciones',
  path: '/comunicaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppCompeticionesRoute = AppCompeticionesRouteImport.update({
  id: '/competiciones',
  path: '/competiciones',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppCargaRoute = AppCargaRouteImport.update({
  id: '/carga',
  path: '/carga',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanasRoute = AppCampanasRouteImport.update({
  id: '/campanas',
  path: '/campanas',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppCajaRoute = AppCajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppBalanceRoute = AppBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppAsistenciaStaffRoute = AppAsistenciaStaffRouteImport.update({
  id: '/asistencia-staff',
  path: '/asistencia-staff',
  getParentRoute: () => AppRoute,
} as any)
const AppAsistenciaRoute = AppAsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => AppRoute,
} as any)
const AppTacticaIndexRoute = AppTacticaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTacticaRoute,
} as any)
const AppRendimientoIndexRoute = AppRendimientoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRendimientoRoute,
} as any)
const AppMedicoIndexRoute = AppMedicoIndexRouteImport.update({
  id: '/medico/',
  path: '/medico/',
  getParentRoute: () => AppRoute,
} as any)
const AppJugadoresIndexRoute = AppJugadoresIndexRouteImport.update({
  id: '/jugadores/',
  path: '/jugadores/',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrenadoresIndexRoute = AppEntrenadoresIndexRouteImport.update({
  id: '/entrenadores/',
  path: '/entrenadores/',
  getParentRoute: () => AppRoute,
} as any)
const AppTacticaVideoRoute = AppTacticaVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => AppTacticaRoute,
} as any)
const AppTacticaSimulacionesRoute = AppTacticaSimulacionesRouteImport.update({
  id: '/simulaciones',
  path: '/simulaciones',
  getParentRoute: () => AppTacticaRoute,
} as any)
const AppTacticaRivalesRoute = AppTacticaRivalesRouteImport.update({
  id: '/rivales',
  path: '/rivales',
  getParentRoute: () => AppTacticaRoute,
} as any)
const AppTacticaPostpartidoRoute = AppTacticaPostpartidoRouteImport.update({
  id: '/postpartido',
  path: '/postpartido',
  getParentRoute: () => AppTacticaRoute,
} as any)
const AppTacticaPlanificacionRoute = AppTacticaPlanificacionRouteImport.update({
  id: '/planificacion',
  path: '/planificacion',
  getParentRoute: () => AppTacticaRoute,
} as any)
const AppTacticaPizarraRoute = AppTacticaPizarraRouteImport.update({
  id: '/pizarra',
  path: '/pizarra',
  getParentRoute: () => AppTacticaRoute,
} as any)
const AppTacticaMatrizRoute = AppTacticaMatrizRouteImport.update({
  id: '/matriz',
  path: '/matriz',
  getParentRoute: () => AppTacticaRoute,
} as any)
const AppTacticaJugadasRoute = AppTacticaJugadasRouteImport.update({
  id: '/jugadas',
  path: '/jugadas',
  getParentRoute: () => AppTacticaRoute,
} as any)
const AppTacticaFormacionesRoute = AppTacticaFormacionesRouteImport.update({
  id: '/formaciones',
  path: '/formaciones',
  getParentRoute: () => AppTacticaRoute,
} as any)
const AppTacticaEstrategiasRoute = AppTacticaEstrategiasRouteImport.update({
  id: '/estrategias',
  path: '/estrategias',
  getParentRoute: () => AppTacticaRoute,
} as any)
const AppTacticaBibliotecaRoute = AppTacticaBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppTacticaRoute,
} as any)
const AppTacticaAnalisisIaRoute = AppTacticaAnalisisIaRouteImport.update({
  id: '/analisis-ia',
  path: '/analisis-ia',
  getParentRoute: () => AppTacticaRoute,
} as any)
const AppRendimientoWellnessRoute = AppRendimientoWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => AppRendimientoRoute,
} as any)
const AppRendimientoTestsRoute = AppRendimientoTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AppRendimientoRoute,
} as any)
const AppRendimientoSportsScienceRoute =
  AppRendimientoSportsScienceRouteImport.update({
    id: '/sports-science',
    path: '/sports-science',
    getParentRoute: () => AppRendimientoRoute,
  } as any)
const AppRendimientoPlanificacionRoute =
  AppRendimientoPlanificacionRouteImport.update({
    id: '/planificacion',
    path: '/planificacion',
    getParentRoute: () => AppRendimientoRoute,
  } as any)
const AppRendimientoLesionesRoute = AppRendimientoLesionesRouteImport.update({
  id: '/lesiones',
  path: '/lesiones',
  getParentRoute: () => AppRendimientoRoute,
} as any)
const AppRendimientoGpsRoute = AppRendimientoGpsRouteImport.update({
  id: '/gps',
  path: '/gps',
  getParentRoute: () => AppRendimientoRoute,
} as any)
const AppRendimientoCargasRoute = AppRendimientoCargasRouteImport.update({
  id: '/cargas',
  path: '/cargas',
  getParentRoute: () => AppRendimientoRoute,
} as any)
const AppMedicoCitasRoute = AppMedicoCitasRouteImport.update({
  id: '/medico/citas',
  path: '/medico/citas',
  getParentRoute: () => AppRoute,
} as any)
const AppJugadoresIdRoute = AppJugadoresIdRouteImport.update({
  id: '/jugadores/$id',
  path: '/jugadores/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRiesgosRoute = AppIaRiesgosRouteImport.update({
  id: '/riesgos',
  path: '/riesgos',
  getParentRoute: () => AppIaRoute,
} as any)
const AppIaRecomendacionesRoute = AppIaRecomendacionesRouteImport.update({
  id: '/recomendaciones',
  path: '/recomendaciones',
  getParentRoute: () => AppIaRoute,
} as any)
const AppIaPrediccionesRoute = AppIaPrediccionesRouteImport.update({
  id: '/predicciones',
  path: '/predicciones',
  getParentRoute: () => AppIaRoute,
} as any)
const AppIaInsightsRoute = AppIaInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppIaRoute,
} as any)
const AppIaAsistenteRoute = AppIaAsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => AppIaRoute,
} as any)
const AppEntrenadoresIdRoute = AppEntrenadoresIdRouteImport.update({
  id: '/entrenadores/$id',
  path: '/entrenadores/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicoJugadorIdRoute = AppMedicoJugadorIdRouteImport.update({
  id: '/medico/jugador/$id',
  path: '/medico/jugador/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inscripcion': typeof InscripcionRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/saas-admin': typeof SaasAdminRoute
  '/signup': typeof SignupRoute
  '/asistencia': typeof AppAsistenciaRoute
  '/asistencia-staff': typeof AppAsistenciaStaffRoute
  '/auditoria': typeof AppAuditoriaRoute
  '/balance': typeof AppBalanceRoute
  '/biblioteca': typeof AppBibliotecaRoute
  '/caja': typeof AppCajaRoute
  '/calendario': typeof AppCalendarioRoute
  '/campanas': typeof AppCampanasRoute
  '/carga': typeof AppCargaRoute
  '/categorias': typeof AppCategoriasRoute
  '/checkin': typeof AppCheckinRoute
  '/coach': typeof AppCoachRoute
  '/competiciones': typeof AppCompeticionesRoute
  '/comunicaciones': typeof AppComunicacionesRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/convocatorias': typeof AppConvocatoriasRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/diario': typeof AppDiarioRoute
  '/disciplinas': typeof AppDisciplinasRoute
  '/egresos': typeof AppEgresosRoute
  '/encargados': typeof AppEncargadosRoute
  '/entrenamientos': typeof AppEntrenamientosRoute
  '/equipos': typeof AppEquiposRoute
  '/evaluaciones': typeof AppEvaluacionesRoute
  '/facturacion': typeof AppFacturacionRoute
  '/finanzas': typeof AppFinanzasRoute
  '/horarios': typeof AppHorariosRoute
  '/ia': typeof AppIaRouteWithChildren
  '/instalaciones': typeof AppInstalacionesRoute
  '/inventario': typeof AppInventarioRoute
  '/leads': typeof AppLeadsRoute
  '/muro': typeof AppMuroRoute
  '/notificaciones': typeof AppNotificacionesRoute
  '/objetivos': typeof AppObjetivosRoute
  '/operacion': typeof AppOperacionRoute
  '/pagos': typeof AppPagosRoute
  '/partidos': typeof AppPartidosRoute
  '/plantillas': typeof AppPlantillasRoute
  '/posiciones': typeof AppPosicionesRoute
  '/prospectos': typeof AppProspectosRoute
  '/pruebas': typeof AppPruebasRoute
  '/rendimiento': typeof AppRendimientoRouteWithChildren
  '/reportes': typeof AppReportesRoute
  '/retencion': typeof AppRetencionRoute
  '/ruta-aprendizaje': typeof AppRutaAprendizajeRoute
  '/sedes': typeof AppSedesRoute
  '/soporte': typeof AppSoporteRoute
  '/tactica': typeof AppTacticaRouteWithChildren
  '/temporadas': typeof AppTemporadasRoute
  '/tienda': typeof AppTiendaRoute
  '/workflows': typeof AppWorkflowsRoute
  '/player-card/$token': typeof PlayerCardTokenRoute
  '/entrenadores/$id': typeof AppEntrenadoresIdRoute
  '/ia/asistente': typeof AppIaAsistenteRoute
  '/ia/insights': typeof AppIaInsightsRoute
  '/ia/predicciones': typeof AppIaPrediccionesRoute
  '/ia/recomendaciones': typeof AppIaRecomendacionesRoute
  '/ia/riesgos': typeof AppIaRiesgosRoute
  '/jugadores/$id': typeof AppJugadoresIdRoute
  '/medico/citas': typeof AppMedicoCitasRoute
  '/rendimiento/cargas': typeof AppRendimientoCargasRoute
  '/rendimiento/gps': typeof AppRendimientoGpsRoute
  '/rendimiento/lesiones': typeof AppRendimientoLesionesRoute
  '/rendimiento/planificacion': typeof AppRendimientoPlanificacionRoute
  '/rendimiento/sports-science': typeof AppRendimientoSportsScienceRoute
  '/rendimiento/tests': typeof AppRendimientoTestsRoute
  '/rendimiento/wellness': typeof AppRendimientoWellnessRoute
  '/tactica/analisis-ia': typeof AppTacticaAnalisisIaRoute
  '/tactica/biblioteca': typeof AppTacticaBibliotecaRoute
  '/tactica/estrategias': typeof AppTacticaEstrategiasRoute
  '/tactica/formaciones': typeof AppTacticaFormacionesRoute
  '/tactica/jugadas': typeof AppTacticaJugadasRoute
  '/tactica/matriz': typeof AppTacticaMatrizRoute
  '/tactica/pizarra': typeof AppTacticaPizarraRoute
  '/tactica/planificacion': typeof AppTacticaPlanificacionRoute
  '/tactica/postpartido': typeof AppTacticaPostpartidoRoute
  '/tactica/rivales': typeof AppTacticaRivalesRoute
  '/tactica/simulaciones': typeof AppTacticaSimulacionesRoute
  '/tactica/video': typeof AppTacticaVideoRoute
  '/entrenadores/': typeof AppEntrenadoresIndexRoute
  '/jugadores/': typeof AppJugadoresIndexRoute
  '/medico/': typeof AppMedicoIndexRoute
  '/rendimiento/': typeof AppRendimientoIndexRoute
  '/tactica/': typeof AppTacticaIndexRoute
  '/medico/jugador/$id': typeof AppMedicoJugadorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inscripcion': typeof InscripcionRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/saas-admin': typeof SaasAdminRoute
  '/signup': typeof SignupRoute
  '/asistencia': typeof AppAsistenciaRoute
  '/asistencia-staff': typeof AppAsistenciaStaffRoute
  '/auditoria': typeof AppAuditoriaRoute
  '/balance': typeof AppBalanceRoute
  '/biblioteca': typeof AppBibliotecaRoute
  '/caja': typeof AppCajaRoute
  '/calendario': typeof AppCalendarioRoute
  '/campanas': typeof AppCampanasRoute
  '/carga': typeof AppCargaRoute
  '/categorias': typeof AppCategoriasRoute
  '/checkin': typeof AppCheckinRoute
  '/coach': typeof AppCoachRoute
  '/competiciones': typeof AppCompeticionesRoute
  '/comunicaciones': typeof AppComunicacionesRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/convocatorias': typeof AppConvocatoriasRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/diario': typeof AppDiarioRoute
  '/disciplinas': typeof AppDisciplinasRoute
  '/egresos': typeof AppEgresosRoute
  '/encargados': typeof AppEncargadosRoute
  '/entrenamientos': typeof AppEntrenamientosRoute
  '/equipos': typeof AppEquiposRoute
  '/evaluaciones': typeof AppEvaluacionesRoute
  '/facturacion': typeof AppFacturacionRoute
  '/finanzas': typeof AppFinanzasRoute
  '/horarios': typeof AppHorariosRoute
  '/ia': typeof AppIaRouteWithChildren
  '/instalaciones': typeof AppInstalacionesRoute
  '/inventario': typeof AppInventarioRoute
  '/leads': typeof AppLeadsRoute
  '/muro': typeof AppMuroRoute
  '/notificaciones': typeof AppNotificacionesRoute
  '/objetivos': typeof AppObjetivosRoute
  '/operacion': typeof AppOperacionRoute
  '/pagos': typeof AppPagosRoute
  '/partidos': typeof AppPartidosRoute
  '/plantillas': typeof AppPlantillasRoute
  '/posiciones': typeof AppPosicionesRoute
  '/prospectos': typeof AppProspectosRoute
  '/pruebas': typeof AppPruebasRoute
  '/reportes': typeof AppReportesRoute
  '/retencion': typeof AppRetencionRoute
  '/ruta-aprendizaje': typeof AppRutaAprendizajeRoute
  '/sedes': typeof AppSedesRoute
  '/soporte': typeof AppSoporteRoute
  '/temporadas': typeof AppTemporadasRoute
  '/tienda': typeof AppTiendaRoute
  '/workflows': typeof AppWorkflowsRoute
  '/player-card/$token': typeof PlayerCardTokenRoute
  '/entrenadores/$id': typeof AppEntrenadoresIdRoute
  '/ia/asistente': typeof AppIaAsistenteRoute
  '/ia/insights': typeof AppIaInsightsRoute
  '/ia/predicciones': typeof AppIaPrediccionesRoute
  '/ia/recomendaciones': typeof AppIaRecomendacionesRoute
  '/ia/riesgos': typeof AppIaRiesgosRoute
  '/jugadores/$id': typeof AppJugadoresIdRoute
  '/medico/citas': typeof AppMedicoCitasRoute
  '/rendimiento/cargas': typeof AppRendimientoCargasRoute
  '/rendimiento/gps': typeof AppRendimientoGpsRoute
  '/rendimiento/lesiones': typeof AppRendimientoLesionesRoute
  '/rendimiento/planificacion': typeof AppRendimientoPlanificacionRoute
  '/rendimiento/sports-science': typeof AppRendimientoSportsScienceRoute
  '/rendimiento/tests': typeof AppRendimientoTestsRoute
  '/rendimiento/wellness': typeof AppRendimientoWellnessRoute
  '/tactica/analisis-ia': typeof AppTacticaAnalisisIaRoute
  '/tactica/biblioteca': typeof AppTacticaBibliotecaRoute
  '/tactica/estrategias': typeof AppTacticaEstrategiasRoute
  '/tactica/formaciones': typeof AppTacticaFormacionesRoute
  '/tactica/jugadas': typeof AppTacticaJugadasRoute
  '/tactica/matriz': typeof AppTacticaMatrizRoute
  '/tactica/pizarra': typeof AppTacticaPizarraRoute
  '/tactica/planificacion': typeof AppTacticaPlanificacionRoute
  '/tactica/postpartido': typeof AppTacticaPostpartidoRoute
  '/tactica/rivales': typeof AppTacticaRivalesRoute
  '/tactica/simulaciones': typeof AppTacticaSimulacionesRoute
  '/tactica/video': typeof AppTacticaVideoRoute
  '/entrenadores': typeof AppEntrenadoresIndexRoute
  '/jugadores': typeof AppJugadoresIndexRoute
  '/medico': typeof AppMedicoIndexRoute
  '/rendimiento': typeof AppRendimientoIndexRoute
  '/tactica': typeof AppTacticaIndexRoute
  '/medico/jugador/$id': typeof AppMedicoJugadorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/inscripcion': typeof InscripcionRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/saas-admin': typeof SaasAdminRoute
  '/signup': typeof SignupRoute
  '/_app/asistencia': typeof AppAsistenciaRoute
  '/_app/asistencia-staff': typeof AppAsistenciaStaffRoute
  '/_app/auditoria': typeof AppAuditoriaRoute
  '/_app/balance': typeof AppBalanceRoute
  '/_app/biblioteca': typeof AppBibliotecaRoute
  '/_app/caja': typeof AppCajaRoute
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/campanas': typeof AppCampanasRoute
  '/_app/carga': typeof AppCargaRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/checkin': typeof AppCheckinRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/competiciones': typeof AppCompeticionesRoute
  '/_app/comunicaciones': typeof AppComunicacionesRoute
  '/_app/configuracion': typeof AppConfiguracionRoute
  '/_app/convocatorias': typeof AppConvocatoriasRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/diario': typeof AppDiarioRoute
  '/_app/disciplinas': typeof AppDisciplinasRoute
  '/_app/egresos': typeof AppEgresosRoute
  '/_app/encargados': typeof AppEncargadosRoute
  '/_app/entrenamientos': typeof AppEntrenamientosRoute
  '/_app/equipos': typeof AppEquiposRoute
  '/_app/evaluaciones': typeof AppEvaluacionesRoute
  '/_app/facturacion': typeof AppFacturacionRoute
  '/_app/finanzas': typeof AppFinanzasRoute
  '/_app/horarios': typeof AppHorariosRoute
  '/_app/ia': typeof AppIaRouteWithChildren
  '/_app/instalaciones': typeof AppInstalacionesRoute
  '/_app/inventario': typeof AppInventarioRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/muro': typeof AppMuroRoute
  '/_app/notificaciones': typeof AppNotificacionesRoute
  '/_app/objetivos': typeof AppObjetivosRoute
  '/_app/operacion': typeof AppOperacionRoute
  '/_app/pagos': typeof AppPagosRoute
  '/_app/partidos': typeof AppPartidosRoute
  '/_app/plantillas': typeof AppPlantillasRoute
  '/_app/posiciones': typeof AppPosicionesRoute
  '/_app/prospectos': typeof AppProspectosRoute
  '/_app/pruebas': typeof AppPruebasRoute
  '/_app/rendimiento': typeof AppRendimientoRouteWithChildren
  '/_app/reportes': typeof AppReportesRoute
  '/_app/retencion': typeof AppRetencionRoute
  '/_app/ruta-aprendizaje': typeof AppRutaAprendizajeRoute
  '/_app/sedes': typeof AppSedesRoute
  '/_app/soporte': typeof AppSoporteRoute
  '/_app/tactica': typeof AppTacticaRouteWithChildren
  '/_app/temporadas': typeof AppTemporadasRoute
  '/_app/tienda': typeof AppTiendaRoute
  '/_app/workflows': typeof AppWorkflowsRoute
  '/player-card/$token': typeof PlayerCardTokenRoute
  '/_app/entrenadores/$id': typeof AppEntrenadoresIdRoute
  '/_app/ia/asistente': typeof AppIaAsistenteRoute
  '/_app/ia/insights': typeof AppIaInsightsRoute
  '/_app/ia/predicciones': typeof AppIaPrediccionesRoute
  '/_app/ia/recomendaciones': typeof AppIaRecomendacionesRoute
  '/_app/ia/riesgos': typeof AppIaRiesgosRoute
  '/_app/jugadores/$id': typeof AppJugadoresIdRoute
  '/_app/medico/citas': typeof AppMedicoCitasRoute
  '/_app/rendimiento/cargas': typeof AppRendimientoCargasRoute
  '/_app/rendimiento/gps': typeof AppRendimientoGpsRoute
  '/_app/rendimiento/lesiones': typeof AppRendimientoLesionesRoute
  '/_app/rendimiento/planificacion': typeof AppRendimientoPlanificacionRoute
  '/_app/rendimiento/sports-science': typeof AppRendimientoSportsScienceRoute
  '/_app/rendimiento/tests': typeof AppRendimientoTestsRoute
  '/_app/rendimiento/wellness': typeof AppRendimientoWellnessRoute
  '/_app/tactica/analisis-ia': typeof AppTacticaAnalisisIaRoute
  '/_app/tactica/biblioteca': typeof AppTacticaBibliotecaRoute
  '/_app/tactica/estrategias': typeof AppTacticaEstrategiasRoute
  '/_app/tactica/formaciones': typeof AppTacticaFormacionesRoute
  '/_app/tactica/jugadas': typeof AppTacticaJugadasRoute
  '/_app/tactica/matriz': typeof AppTacticaMatrizRoute
  '/_app/tactica/pizarra': typeof AppTacticaPizarraRoute
  '/_app/tactica/planificacion': typeof AppTacticaPlanificacionRoute
  '/_app/tactica/postpartido': typeof AppTacticaPostpartidoRoute
  '/_app/tactica/rivales': typeof AppTacticaRivalesRoute
  '/_app/tactica/simulaciones': typeof AppTacticaSimulacionesRoute
  '/_app/tactica/video': typeof AppTacticaVideoRoute
  '/_app/entrenadores/': typeof AppEntrenadoresIndexRoute
  '/_app/jugadores/': typeof AppJugadoresIndexRoute
  '/_app/medico/': typeof AppMedicoIndexRoute
  '/_app/rendimiento/': typeof AppRendimientoIndexRoute
  '/_app/tactica/': typeof AppTacticaIndexRoute
  '/_app/medico/jugador/$id': typeof AppMedicoJugadorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inscripcion'
    | '/landing'
    | '/login'
    | '/saas-admin'
    | '/signup'
    | '/asistencia'
    | '/asistencia-staff'
    | '/auditoria'
    | '/balance'
    | '/biblioteca'
    | '/caja'
    | '/calendario'
    | '/campanas'
    | '/carga'
    | '/categorias'
    | '/checkin'
    | '/coach'
    | '/competiciones'
    | '/comunicaciones'
    | '/configuracion'
    | '/convocatorias'
    | '/crm'
    | '/dashboard'
    | '/diario'
    | '/disciplinas'
    | '/egresos'
    | '/encargados'
    | '/entrenamientos'
    | '/equipos'
    | '/evaluaciones'
    | '/facturacion'
    | '/finanzas'
    | '/horarios'
    | '/ia'
    | '/instalaciones'
    | '/inventario'
    | '/leads'
    | '/muro'
    | '/notificaciones'
    | '/objetivos'
    | '/operacion'
    | '/pagos'
    | '/partidos'
    | '/plantillas'
    | '/posiciones'
    | '/prospectos'
    | '/pruebas'
    | '/rendimiento'
    | '/reportes'
    | '/retencion'
    | '/ruta-aprendizaje'
    | '/sedes'
    | '/soporte'
    | '/tactica'
    | '/temporadas'
    | '/tienda'
    | '/workflows'
    | '/player-card/$token'
    | '/entrenadores/$id'
    | '/ia/asistente'
    | '/ia/insights'
    | '/ia/predicciones'
    | '/ia/recomendaciones'
    | '/ia/riesgos'
    | '/jugadores/$id'
    | '/medico/citas'
    | '/rendimiento/cargas'
    | '/rendimiento/gps'
    | '/rendimiento/lesiones'
    | '/rendimiento/planificacion'
    | '/rendimiento/sports-science'
    | '/rendimiento/tests'
    | '/rendimiento/wellness'
    | '/tactica/analisis-ia'
    | '/tactica/biblioteca'
    | '/tactica/estrategias'
    | '/tactica/formaciones'
    | '/tactica/jugadas'
    | '/tactica/matriz'
    | '/tactica/pizarra'
    | '/tactica/planificacion'
    | '/tactica/postpartido'
    | '/tactica/rivales'
    | '/tactica/simulaciones'
    | '/tactica/video'
    | '/entrenadores/'
    | '/jugadores/'
    | '/medico/'
    | '/rendimiento/'
    | '/tactica/'
    | '/medico/jugador/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inscripcion'
    | '/landing'
    | '/login'
    | '/saas-admin'
    | '/signup'
    | '/asistencia'
    | '/asistencia-staff'
    | '/auditoria'
    | '/balance'
    | '/biblioteca'
    | '/caja'
    | '/calendario'
    | '/campanas'
    | '/carga'
    | '/categorias'
    | '/checkin'
    | '/coach'
    | '/competiciones'
    | '/comunicaciones'
    | '/configuracion'
    | '/convocatorias'
    | '/crm'
    | '/dashboard'
    | '/diario'
    | '/disciplinas'
    | '/egresos'
    | '/encargados'
    | '/entrenamientos'
    | '/equipos'
    | '/evaluaciones'
    | '/facturacion'
    | '/finanzas'
    | '/horarios'
    | '/ia'
    | '/instalaciones'
    | '/inventario'
    | '/leads'
    | '/muro'
    | '/notificaciones'
    | '/objetivos'
    | '/operacion'
    | '/pagos'
    | '/partidos'
    | '/plantillas'
    | '/posiciones'
    | '/prospectos'
    | '/pruebas'
    | '/reportes'
    | '/retencion'
    | '/ruta-aprendizaje'
    | '/sedes'
    | '/soporte'
    | '/temporadas'
    | '/tienda'
    | '/workflows'
    | '/player-card/$token'
    | '/entrenadores/$id'
    | '/ia/asistente'
    | '/ia/insights'
    | '/ia/predicciones'
    | '/ia/recomendaciones'
    | '/ia/riesgos'
    | '/jugadores/$id'
    | '/medico/citas'
    | '/rendimiento/cargas'
    | '/rendimiento/gps'
    | '/rendimiento/lesiones'
    | '/rendimiento/planificacion'
    | '/rendimiento/sports-science'
    | '/rendimiento/tests'
    | '/rendimiento/wellness'
    | '/tactica/analisis-ia'
    | '/tactica/biblioteca'
    | '/tactica/estrategias'
    | '/tactica/formaciones'
    | '/tactica/jugadas'
    | '/tactica/matriz'
    | '/tactica/pizarra'
    | '/tactica/planificacion'
    | '/tactica/postpartido'
    | '/tactica/rivales'
    | '/tactica/simulaciones'
    | '/tactica/video'
    | '/entrenadores'
    | '/jugadores'
    | '/medico'
    | '/rendimiento'
    | '/tactica'
    | '/medico/jugador/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/inscripcion'
    | '/landing'
    | '/login'
    | '/saas-admin'
    | '/signup'
    | '/_app/asistencia'
    | '/_app/asistencia-staff'
    | '/_app/auditoria'
    | '/_app/balance'
    | '/_app/biblioteca'
    | '/_app/caja'
    | '/_app/calendario'
    | '/_app/campanas'
    | '/_app/carga'
    | '/_app/categorias'
    | '/_app/checkin'
    | '/_app/coach'
    | '/_app/competiciones'
    | '/_app/comunicaciones'
    | '/_app/configuracion'
    | '/_app/convocatorias'
    | '/_app/crm'
    | '/_app/dashboard'
    | '/_app/diario'
    | '/_app/disciplinas'
    | '/_app/egresos'
    | '/_app/encargados'
    | '/_app/entrenamientos'
    | '/_app/equipos'
    | '/_app/evaluaciones'
    | '/_app/facturacion'
    | '/_app/finanzas'
    | '/_app/horarios'
    | '/_app/ia'
    | '/_app/instalaciones'
    | '/_app/inventario'
    | '/_app/leads'
    | '/_app/muro'
    | '/_app/notificaciones'
    | '/_app/objetivos'
    | '/_app/operacion'
    | '/_app/pagos'
    | '/_app/partidos'
    | '/_app/plantillas'
    | '/_app/posiciones'
    | '/_app/prospectos'
    | '/_app/pruebas'
    | '/_app/rendimiento'
    | '/_app/reportes'
    | '/_app/retencion'
    | '/_app/ruta-aprendizaje'
    | '/_app/sedes'
    | '/_app/soporte'
    | '/_app/tactica'
    | '/_app/temporadas'
    | '/_app/tienda'
    | '/_app/workflows'
    | '/player-card/$token'
    | '/_app/entrenadores/$id'
    | '/_app/ia/asistente'
    | '/_app/ia/insights'
    | '/_app/ia/predicciones'
    | '/_app/ia/recomendaciones'
    | '/_app/ia/riesgos'
    | '/_app/jugadores/$id'
    | '/_app/medico/citas'
    | '/_app/rendimiento/cargas'
    | '/_app/rendimiento/gps'
    | '/_app/rendimiento/lesiones'
    | '/_app/rendimiento/planificacion'
    | '/_app/rendimiento/sports-science'
    | '/_app/rendimiento/tests'
    | '/_app/rendimiento/wellness'
    | '/_app/tactica/analisis-ia'
    | '/_app/tactica/biblioteca'
    | '/_app/tactica/estrategias'
    | '/_app/tactica/formaciones'
    | '/_app/tactica/jugadas'
    | '/_app/tactica/matriz'
    | '/_app/tactica/pizarra'
    | '/_app/tactica/planificacion'
    | '/_app/tactica/postpartido'
    | '/_app/tactica/rivales'
    | '/_app/tactica/simulaciones'
    | '/_app/tactica/video'
    | '/_app/entrenadores/'
    | '/_app/jugadores/'
    | '/_app/medico/'
    | '/_app/rendimiento/'
    | '/_app/tactica/'
    | '/_app/medico/jugador/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  InscripcionRoute: typeof InscripcionRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  SaasAdminRoute: typeof SaasAdminRoute
  SignupRoute: typeof SignupRoute
  PlayerCardTokenRoute: typeof PlayerCardTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saas-admin': {
      id: '/saas-admin'
      path: '/saas-admin'
      fullPath: '/saas-admin'
      preLoaderRoute: typeof SaasAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscripcion': {
      id: '/inscripcion'
      path: '/inscripcion'
      fullPath: '/inscripcion'
      preLoaderRoute: typeof InscripcionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player-card/$token': {
      id: '/player-card/$token'
      path: '/player-card/$token'
      fullPath: '/player-card/$token'
      preLoaderRoute: typeof PlayerCardTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tienda': {
      id: '/_app/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof AppTiendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/temporadas': {
      id: '/_app/temporadas'
      path: '/temporadas'
      fullPath: '/temporadas'
      preLoaderRoute: typeof AppTemporadasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tactica': {
      id: '/_app/tactica'
      path: '/tactica'
      fullPath: '/tactica'
      preLoaderRoute: typeof AppTacticaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/soporte': {
      id: '/_app/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof AppSoporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sedes': {
      id: '/_app/sedes'
      path: '/sedes'
      fullPath: '/sedes'
      preLoaderRoute: typeof AppSedesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ruta-aprendizaje': {
      id: '/_app/ruta-aprendizaje'
      path: '/ruta-aprendizaje'
      fullPath: '/ruta-aprendizaje'
      preLoaderRoute: typeof AppRutaAprendizajeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/retencion': {
      id: '/_app/retencion'
      path: '/retencion'
      fullPath: '/retencion'
      preLoaderRoute: typeof AppRetencionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reportes': {
      id: '/_app/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AppReportesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rendimiento': {
      id: '/_app/rendimiento'
      path: '/rendimiento'
      fullPath: '/rendimiento'
      preLoaderRoute: typeof AppRendimientoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pruebas': {
      id: '/_app/pruebas'
      path: '/pruebas'
      fullPath: '/pruebas'
      preLoaderRoute: typeof AppPruebasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospectos': {
      id: '/_app/prospectos'
      path: '/prospectos'
      fullPath: '/prospectos'
      preLoaderRoute: typeof AppProspectosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posiciones': {
      id: '/_app/posiciones'
      path: '/posiciones'
      fullPath: '/posiciones'
      preLoaderRoute: typeof AppPosicionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plantillas': {
      id: '/_app/plantillas'
      path: '/plantillas'
      fullPath: '/plantillas'
      preLoaderRoute: typeof AppPlantillasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partidos': {
      id: '/_app/partidos'
      path: '/partidos'
      fullPath: '/partidos'
      preLoaderRoute: typeof AppPartidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pagos': {
      id: '/_app/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof AppPagosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operacion': {
      id: '/_app/operacion'
      path: '/operacion'
      fullPath: '/operacion'
      preLoaderRoute: typeof AppOperacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/objetivos': {
      id: '/_app/objetivos'
      path: '/objetivos'
      fullPath: '/objetivos'
      preLoaderRoute: typeof AppObjetivosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificaciones': {
      id: '/_app/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof AppNotificacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/muro': {
      id: '/_app/muro'
      path: '/muro'
      fullPath: '/muro'
      preLoaderRoute: typeof AppMuroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventario': {
      id: '/_app/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AppInventarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/instalaciones': {
      id: '/_app/instalaciones'
      path: '/instalaciones'
      fullPath: '/instalaciones'
      preLoaderRoute: typeof AppInstalacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia': {
      id: '/_app/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/horarios': {
      id: '/_app/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof AppHorariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finanzas': {
      id: '/_app/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof AppFinanzasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/facturacion': {
      id: '/_app/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof AppFacturacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evaluaciones': {
      id: '/_app/evaluaciones'
      path: '/evaluaciones'
      fullPath: '/evaluaciones'
      preLoaderRoute: typeof AppEvaluacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipos': {
      id: '/_app/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof AppEquiposRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entrenamientos': {
      id: '/_app/entrenamientos'
      path: '/entrenamientos'
      fullPath: '/entrenamientos'
      preLoaderRoute: typeof AppEntrenamientosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/encargados': {
      id: '/_app/encargados'
      path: '/encargados'
      fullPath: '/encargados'
      preLoaderRoute: typeof AppEncargadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/egresos': {
      id: '/_app/egresos'
      path: '/egresos'
      fullPath: '/egresos'
      preLoaderRoute: typeof AppEgresosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disciplinas': {
      id: '/_app/disciplinas'
      path: '/disciplinas'
      fullPath: '/disciplinas'
      preLoaderRoute: typeof AppDisciplinasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diario': {
      id: '/_app/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AppDiarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/convocatorias': {
      id: '/_app/convocatorias'
      path: '/convocatorias'
      fullPath: '/convocatorias'
      preLoaderRoute: typeof AppConvocatoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion': {
      id: '/_app/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comunicaciones': {
      id: '/_app/comunicaciones'
      path: '/comunicaciones'
      fullPath: '/comunicaciones'
      preLoaderRoute: typeof AppComunicacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/competiciones': {
      id: '/_app/competiciones'
      path: '/competiciones'
      fullPath: '/competiciones'
      preLoaderRoute: typeof AppCompeticionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkin': {
      id: '/_app/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carga': {
      id: '/_app/carga'
      path: '/carga'
      fullPath: '/carga'
      preLoaderRoute: typeof AppCargaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanas': {
      id: '/_app/campanas'
      path: '/campanas'
      fullPath: '/campanas'
      preLoaderRoute: typeof AppCampanasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/caja': {
      id: '/_app/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof AppCajaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca': {
      id: '/_app/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/balance': {
      id: '/_app/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof AppBalanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auditoria': {
      id: '/_app/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/asistencia-staff': {
      id: '/_app/asistencia-staff'
      path: '/asistencia-staff'
      fullPath: '/asistencia-staff'
      preLoaderRoute: typeof AppAsistenciaStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/asistencia': {
      id: '/_app/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof AppAsistenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tactica/': {
      id: '/_app/tactica/'
      path: '/'
      fullPath: '/tactica/'
      preLoaderRoute: typeof AppTacticaIndexRouteImport
      parentRoute: typeof AppTacticaRoute
    }
    '/_app/rendimiento/': {
      id: '/_app/rendimiento/'
      path: '/'
      fullPath: '/rendimiento/'
      preLoaderRoute: typeof AppRendimientoIndexRouteImport
      parentRoute: typeof AppRendimientoRoute
    }
    '/_app/medico/': {
      id: '/_app/medico/'
      path: '/medico'
      fullPath: '/medico/'
      preLoaderRoute: typeof AppMedicoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jugadores/': {
      id: '/_app/jugadores/'
      path: '/jugadores'
      fullPath: '/jugadores/'
      preLoaderRoute: typeof AppJugadoresIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entrenadores/': {
      id: '/_app/entrenadores/'
      path: '/entrenadores'
      fullPath: '/entrenadores/'
      preLoaderRoute: typeof AppEntrenadoresIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tactica/video': {
      id: '/_app/tactica/video'
      path: '/video'
      fullPath: '/tactica/video'
      preLoaderRoute: typeof AppTacticaVideoRouteImport
      parentRoute: typeof AppTacticaRoute
    }
    '/_app/tactica/simulaciones': {
      id: '/_app/tactica/simulaciones'
      path: '/simulaciones'
      fullPath: '/tactica/simulaciones'
      preLoaderRoute: typeof AppTacticaSimulacionesRouteImport
      parentRoute: typeof AppTacticaRoute
    }
    '/_app/tactica/rivales': {
      id: '/_app/tactica/rivales'
      path: '/rivales'
      fullPath: '/tactica/rivales'
      preLoaderRoute: typeof AppTacticaRivalesRouteImport
      parentRoute: typeof AppTacticaRoute
    }
    '/_app/tactica/postpartido': {
      id: '/_app/tactica/postpartido'
      path: '/postpartido'
      fullPath: '/tactica/postpartido'
      preLoaderRoute: typeof AppTacticaPostpartidoRouteImport
      parentRoute: typeof AppTacticaRoute
    }
    '/_app/tactica/planificacion': {
      id: '/_app/tactica/planificacion'
      path: '/planificacion'
      fullPath: '/tactica/planificacion'
      preLoaderRoute: typeof AppTacticaPlanificacionRouteImport
      parentRoute: typeof AppTacticaRoute
    }
    '/_app/tactica/pizarra': {
      id: '/_app/tactica/pizarra'
      path: '/pizarra'
      fullPath: '/tactica/pizarra'
      preLoaderRoute: typeof AppTacticaPizarraRouteImport
      parentRoute: typeof AppTacticaRoute
    }
    '/_app/tactica/matriz': {
      id: '/_app/tactica/matriz'
      path: '/matriz'
      fullPath: '/tactica/matriz'
      preLoaderRoute: typeof AppTacticaMatrizRouteImport
      parentRoute: typeof AppTacticaRoute
    }
    '/_app/tactica/jugadas': {
      id: '/_app/tactica/jugadas'
      path: '/jugadas'
      fullPath: '/tactica/jugadas'
      preLoaderRoute: typeof AppTacticaJugadasRouteImport
      parentRoute: typeof AppTacticaRoute
    }
    '/_app/tactica/formaciones': {
      id: '/_app/tactica/formaciones'
      path: '/formaciones'
      fullPath: '/tactica/formaciones'
      preLoaderRoute: typeof AppTacticaFormacionesRouteImport
      parentRoute: typeof AppTacticaRoute
    }
    '/_app/tactica/estrategias': {
      id: '/_app/tactica/estrategias'
      path: '/estrategias'
      fullPath: '/tactica/estrategias'
      preLoaderRoute: typeof AppTacticaEstrategiasRouteImport
      parentRoute: typeof AppTacticaRoute
    }
    '/_app/tactica/biblioteca': {
      id: '/_app/tactica/biblioteca'
      path: '/biblioteca'
      fullPath: '/tactica/biblioteca'
      preLoaderRoute: typeof AppTacticaBibliotecaRouteImport
      parentRoute: typeof AppTacticaRoute
    }
    '/_app/tactica/analisis-ia': {
      id: '/_app/tactica/analisis-ia'
      path: '/analisis-ia'
      fullPath: '/tactica/analisis-ia'
      preLoaderRoute: typeof AppTacticaAnalisisIaRouteImport
      parentRoute: typeof AppTacticaRoute
    }
    '/_app/rendimiento/wellness': {
      id: '/_app/rendimiento/wellness'
      path: '/wellness'
      fullPath: '/rendimiento/wellness'
      preLoaderRoute: typeof AppRendimientoWellnessRouteImport
      parentRoute: typeof AppRendimientoRoute
    }
    '/_app/rendimiento/tests': {
      id: '/_app/rendimiento/tests'
      path: '/tests'
      fullPath: '/rendimiento/tests'
      preLoaderRoute: typeof AppRendimientoTestsRouteImport
      parentRoute: typeof AppRendimientoRoute
    }
    '/_app/rendimiento/sports-science': {
      id: '/_app/rendimiento/sports-science'
      path: '/sports-science'
      fullPath: '/rendimiento/sports-science'
      preLoaderRoute: typeof AppRendimientoSportsScienceRouteImport
      parentRoute: typeof AppRendimientoRoute
    }
    '/_app/rendimiento/planificacion': {
      id: '/_app/rendimiento/planificacion'
      path: '/planificacion'
      fullPath: '/rendimiento/planificacion'
      preLoaderRoute: typeof AppRendimientoPlanificacionRouteImport
      parentRoute: typeof AppRendimientoRoute
    }
    '/_app/rendimiento/lesiones': {
      id: '/_app/rendimiento/lesiones'
      path: '/lesiones'
      fullPath: '/rendimiento/lesiones'
      preLoaderRoute: typeof AppRendimientoLesionesRouteImport
      parentRoute: typeof AppRendimientoRoute
    }
    '/_app/rendimiento/gps': {
      id: '/_app/rendimiento/gps'
      path: '/gps'
      fullPath: '/rendimiento/gps'
      preLoaderRoute: typeof AppRendimientoGpsRouteImport
      parentRoute: typeof AppRendimientoRoute
    }
    '/_app/rendimiento/cargas': {
      id: '/_app/rendimiento/cargas'
      path: '/cargas'
      fullPath: '/rendimiento/cargas'
      preLoaderRoute: typeof AppRendimientoCargasRouteImport
      parentRoute: typeof AppRendimientoRoute
    }
    '/_app/medico/citas': {
      id: '/_app/medico/citas'
      path: '/medico/citas'
      fullPath: '/medico/citas'
      preLoaderRoute: typeof AppMedicoCitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jugadores/$id': {
      id: '/_app/jugadores/$id'
      path: '/jugadores/$id'
      fullPath: '/jugadores/$id'
      preLoaderRoute: typeof AppJugadoresIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia/riesgos': {
      id: '/_app/ia/riesgos'
      path: '/riesgos'
      fullPath: '/ia/riesgos'
      preLoaderRoute: typeof AppIaRiesgosRouteImport
      parentRoute: typeof AppIaRoute
    }
    '/_app/ia/recomendaciones': {
      id: '/_app/ia/recomendaciones'
      path: '/recomendaciones'
      fullPath: '/ia/recomendaciones'
      preLoaderRoute: typeof AppIaRecomendacionesRouteImport
      parentRoute: typeof AppIaRoute
    }
    '/_app/ia/predicciones': {
      id: '/_app/ia/predicciones'
      path: '/predicciones'
      fullPath: '/ia/predicciones'
      preLoaderRoute: typeof AppIaPrediccionesRouteImport
      parentRoute: typeof AppIaRoute
    }
    '/_app/ia/insights': {
      id: '/_app/ia/insights'
      path: '/insights'
      fullPath: '/ia/insights'
      preLoaderRoute: typeof AppIaInsightsRouteImport
      parentRoute: typeof AppIaRoute
    }
    '/_app/ia/asistente': {
      id: '/_app/ia/asistente'
      path: '/asistente'
      fullPath: '/ia/asistente'
      preLoaderRoute: typeof AppIaAsistenteRouteImport
      parentRoute: typeof AppIaRoute
    }
    '/_app/entrenadores/$id': {
      id: '/_app/entrenadores/$id'
      path: '/entrenadores/$id'
      fullPath: '/entrenadores/$id'
      preLoaderRoute: typeof AppEntrenadoresIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medico/jugador/$id': {
      id: '/_app/medico/jugador/$id'
      path: '/medico/jugador/$id'
      fullPath: '/medico/jugador/$id'
      preLoaderRoute: typeof AppMedicoJugadorIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppIaRouteChildren {
  AppIaAsistenteRoute: typeof AppIaAsistenteRoute
  AppIaInsightsRoute: typeof AppIaInsightsRoute
  AppIaPrediccionesRoute: typeof AppIaPrediccionesRoute
  AppIaRecomendacionesRoute: typeof AppIaRecomendacionesRoute
  AppIaRiesgosRoute: typeof AppIaRiesgosRoute
}

const AppIaRouteChildren: AppIaRouteChildren = {
  AppIaAsistenteRoute: AppIaAsistenteRoute,
  AppIaInsightsRoute: AppIaInsightsRoute,
  AppIaPrediccionesRoute: AppIaPrediccionesRoute,
  AppIaRecomendacionesRoute: AppIaRecomendacionesRoute,
  AppIaRiesgosRoute: AppIaRiesgosRoute,
}

const AppIaRouteWithChildren = AppIaRoute._addFileChildren(AppIaRouteChildren)

interface AppRendimientoRouteChildren {
  AppRendimientoCargasRoute: typeof AppRendimientoCargasRoute
  AppRendimientoGpsRoute: typeof AppRendimientoGpsRoute
  AppRendimientoLesionesRoute: typeof AppRendimientoLesionesRoute
  AppRendimientoPlanificacionRoute: typeof AppRendimientoPlanificacionRoute
  AppRendimientoSportsScienceRoute: typeof AppRendimientoSportsScienceRoute
  AppRendimientoTestsRoute: typeof AppRendimientoTestsRoute
  AppRendimientoWellnessRoute: typeof AppRendimientoWellnessRoute
  AppRendimientoIndexRoute: typeof AppRendimientoIndexRoute
}

const AppRendimientoRouteChildren: AppRendimientoRouteChildren = {
  AppRendimientoCargasRoute: AppRendimientoCargasRoute,
  AppRendimientoGpsRoute: AppRendimientoGpsRoute,
  AppRendimientoLesionesRoute: AppRendimientoLesionesRoute,
  AppRendimientoPlanificacionRoute: AppRendimientoPlanificacionRoute,
  AppRendimientoSportsScienceRoute: AppRendimientoSportsScienceRoute,
  AppRendimientoTestsRoute: AppRendimientoTestsRoute,
  AppRendimientoWellnessRoute: AppRendimientoWellnessRoute,
  AppRendimientoIndexRoute: AppRendimientoIndexRoute,
}

const AppRendimientoRouteWithChildren = AppRendimientoRoute._addFileChildren(
  AppRendimientoRouteChildren,
)

interface AppTacticaRouteChildren {
  AppTacticaAnalisisIaRoute: typeof AppTacticaAnalisisIaRoute
  AppTacticaBibliotecaRoute: typeof AppTacticaBibliotecaRoute
  AppTacticaEstrategiasRoute: typeof AppTacticaEstrategiasRoute
  AppTacticaFormacionesRoute: typeof AppTacticaFormacionesRoute
  AppTacticaJugadasRoute: typeof AppTacticaJugadasRoute
  AppTacticaMatrizRoute: typeof AppTacticaMatrizRoute
  AppTacticaPizarraRoute: typeof AppTacticaPizarraRoute
  AppTacticaPlanificacionRoute: typeof AppTacticaPlanificacionRoute
  AppTacticaPostpartidoRoute: typeof AppTacticaPostpartidoRoute
  AppTacticaRivalesRoute: typeof AppTacticaRivalesRoute
  AppTacticaSimulacionesRoute: typeof AppTacticaSimulacionesRoute
  AppTacticaVideoRoute: typeof AppTacticaVideoRoute
  AppTacticaIndexRoute: typeof AppTacticaIndexRoute
}

const AppTacticaRouteChildren: AppTacticaRouteChildren = {
  AppTacticaAnalisisIaRoute: AppTacticaAnalisisIaRoute,
  AppTacticaBibliotecaRoute: AppTacticaBibliotecaRoute,
  AppTacticaEstrategiasRoute: AppTacticaEstrategiasRoute,
  AppTacticaFormacionesRoute: AppTacticaFormacionesRoute,
  AppTacticaJugadasRoute: AppTacticaJugadasRoute,
  AppTacticaMatrizRoute: AppTacticaMatrizRoute,
  AppTacticaPizarraRoute: AppTacticaPizarraRoute,
  AppTacticaPlanificacionRoute: AppTacticaPlanificacionRoute,
  AppTacticaPostpartidoRoute: AppTacticaPostpartidoRoute,
  AppTacticaRivalesRoute: AppTacticaRivalesRoute,
  AppTacticaSimulacionesRoute: AppTacticaSimulacionesRoute,
  AppTacticaVideoRoute: AppTacticaVideoRoute,
  AppTacticaIndexRoute: AppTacticaIndexRoute,
}

const AppTacticaRouteWithChildren = AppTacticaRoute._addFileChildren(
  AppTacticaRouteChildren,
)

interface AppRouteChildren {
  AppAsistenciaRoute: typeof AppAsistenciaRoute
  AppAsistenciaStaffRoute: typeof AppAsistenciaStaffRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppBalanceRoute: typeof AppBalanceRoute
  AppBibliotecaRoute: typeof AppBibliotecaRoute
  AppCajaRoute: typeof AppCajaRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppCampanasRoute: typeof AppCampanasRoute
  AppCargaRoute: typeof AppCargaRoute
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppCheckinRoute: typeof AppCheckinRoute
  AppCoachRoute: typeof AppCoachRoute
  AppCompeticionesRoute: typeof AppCompeticionesRoute
  AppComunicacionesRoute: typeof AppComunicacionesRoute
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppConvocatoriasRoute: typeof AppConvocatoriasRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiarioRoute: typeof AppDiarioRoute
  AppDisciplinasRoute: typeof AppDisciplinasRoute
  AppEgresosRoute: typeof AppEgresosRoute
  AppEncargadosRoute: typeof AppEncargadosRoute
  AppEntrenamientosRoute: typeof AppEntrenamientosRoute
  AppEquiposRoute: typeof AppEquiposRoute
  AppEvaluacionesRoute: typeof AppEvaluacionesRoute
  AppFacturacionRoute: typeof AppFacturacionRoute
  AppFinanzasRoute: typeof AppFinanzasRoute
  AppHorariosRoute: typeof AppHorariosRoute
  AppIaRoute: typeof AppIaRouteWithChildren
  AppInstalacionesRoute: typeof AppInstalacionesRoute
  AppInventarioRoute: typeof AppInventarioRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMuroRoute: typeof AppMuroRoute
  AppNotificacionesRoute: typeof AppNotificacionesRoute
  AppObjetivosRoute: typeof AppObjetivosRoute
  AppOperacionRoute: typeof AppOperacionRoute
  AppPagosRoute: typeof AppPagosRoute
  AppPartidosRoute: typeof AppPartidosRoute
  AppPlantillasRoute: typeof AppPlantillasRoute
  AppPosicionesRoute: typeof AppPosicionesRoute
  AppProspectosRoute: typeof AppProspectosRoute
  AppPruebasRoute: typeof AppPruebasRoute
  AppRendimientoRoute: typeof AppRendimientoRouteWithChildren
  AppReportesRoute: typeof AppReportesRoute
  AppRetencionRoute: typeof AppRetencionRoute
  AppRutaAprendizajeRoute: typeof AppRutaAprendizajeRoute
  AppSedesRoute: typeof AppSedesRoute
  AppSoporteRoute: typeof AppSoporteRoute
  AppTacticaRoute: typeof AppTacticaRouteWithChildren
  AppTemporadasRoute: typeof AppTemporadasRoute
  AppTiendaRoute: typeof AppTiendaRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppEntrenadoresIdRoute: typeof AppEntrenadoresIdRoute
  AppJugadoresIdRoute: typeof AppJugadoresIdRoute
  AppMedicoCitasRoute: typeof AppMedicoCitasRoute
  AppEntrenadoresIndexRoute: typeof AppEntrenadoresIndexRoute
  AppJugadoresIndexRoute: typeof AppJugadoresIndexRoute
  AppMedicoIndexRoute: typeof AppMedicoIndexRoute
  AppMedicoJugadorIdRoute: typeof AppMedicoJugadorIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAsistenciaRoute: AppAsistenciaRoute,
  AppAsistenciaStaffRoute: AppAsistenciaStaffRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppBalanceRoute: AppBalanceRoute,
  AppBibliotecaRoute: AppBibliotecaRoute,
  AppCajaRoute: AppCajaRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppCampanasRoute: AppCampanasRoute,
  AppCargaRoute: AppCargaRoute,
  AppCategoriasRoute: AppCategoriasRoute,
  AppCheckinRoute: AppCheckinRoute,
  AppCoachRoute: AppCoachRoute,
  AppCompeticionesRoute: AppCompeticionesRoute,
  AppComunicacionesRoute: AppComunicacionesRoute,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppConvocatoriasRoute: AppConvocatoriasRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDiarioRoute: AppDiarioRoute,
  AppDisciplinasRoute: AppDisciplinasRoute,
  AppEgresosRoute: AppEgresosRoute,
  AppEncargadosRoute: AppEncargadosRoute,
  AppEntrenamientosRoute: AppEntrenamientosRoute,
  AppEquiposRoute: AppEquiposRoute,
  AppEvaluacionesRoute: AppEvaluacionesRoute,
  AppFacturacionRoute: AppFacturacionRoute,
  AppFinanzasRoute: AppFinanzasRoute,
  AppHorariosRoute: AppHorariosRoute,
  AppIaRoute: AppIaRouteWithChildren,
  AppInstalacionesRoute: AppInstalacionesRoute,
  AppInventarioRoute: AppInventarioRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMuroRoute: AppMuroRoute,
  AppNotificacionesRoute: AppNotificacionesRoute,
  AppObjetivosRoute: AppObjetivosRoute,
  AppOperacionRoute: AppOperacionRoute,
  AppPagosRoute: AppPagosRoute,
  AppPartidosRoute: AppPartidosRoute,
  AppPlantillasRoute: AppPlantillasRoute,
  AppPosicionesRoute: AppPosicionesRoute,
  AppProspectosRoute: AppProspectosRoute,
  AppPruebasRoute: AppPruebasRoute,
  AppRendimientoRoute: AppRendimientoRouteWithChildren,
  AppReportesRoute: AppReportesRoute,
  AppRetencionRoute: AppRetencionRoute,
  AppRutaAprendizajeRoute: AppRutaAprendizajeRoute,
  AppSedesRoute: AppSedesRoute,
  AppSoporteRoute: AppSoporteRoute,
  AppTacticaRoute: AppTacticaRouteWithChildren,
  AppTemporadasRoute: AppTemporadasRoute,
  AppTiendaRoute: AppTiendaRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppEntrenadoresIdRoute: AppEntrenadoresIdRoute,
  AppJugadoresIdRoute: AppJugadoresIdRoute,
  AppMedicoCitasRoute: AppMedicoCitasRoute,
  AppEntrenadoresIndexRoute: AppEntrenadoresIndexRoute,
  AppJugadoresIndexRoute: AppJugadoresIndexRoute,
  AppMedicoIndexRoute: AppMedicoIndexRoute,
  AppMedicoJugadorIdRoute: AppMedicoJugadorIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  InscripcionRoute: InscripcionRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  SaasAdminRoute: SaasAdminRoute,
  SignupRoute: SignupRoute,
  PlayerCardTokenRoute: PlayerCardTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
